anonymousFunc = function () {
    window.cachedFileNames["jsb_pagetemplates"] = "jsb_pagetemplates"
    if (!window.cached_jsb_pagetemplates) window.cached_jsb_pagetemplates = {}
    var z = "{ index:15 },\xFE";
    z += "\xFE";
    z += "{name:'centerview', index:16, label:'Center view', datatype: 'string', primarykey:false, width:30, control:'dropdownbox', required: false, notblank: false, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" },\xFE";
    z += "{name:'centermaster', index:17, label:'Master view', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:0, reflist: \"false,0;true,1\" },\xFE";
    z += "{ index:20 },\xFE";
    z += "{ index:25},\xFE";
    z += "\xFE";
    z += "{name:'backbtn', index:26, label:'Back Btn', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:0, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'cancelbtn', index:27, label:'Cancel Btn', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:0, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'canceltxt', index:28, label:'Cancel Text', required: false, datatype: 'string', width:90, control:'textbox', canedit:true, defaultvalue:\"Cancel\" },\xFE";
    z += "\xFE";
    z += "{ index:30 },\xFE";
    z += "{name:'northview', index:31, label:'Top View', datatype: 'string', primarykey:false, width:30, control:'dropdownbox', required: false, notblank: false, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" },\xFE";
    z += "{name:'northmaster', index:17, label:'Master view', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:0, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewfixed', index:32, label:'Top fixed', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewslidable', index:33, label:'Top slidable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewclosable', index:34, label:'Top closable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewinitclosed', index:35, label:'Northv InitShut', width:12, control:'checkbox', canedit:true, required: false, notblank: true,  reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewinithidden', index:36, label:'Top initHidden', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewminsize', index:37, label:'Top MinSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewmaxsize', index:38, label:'Top MaxSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'northviewstartsize', defaultvalue:200, index:39, label:'Top Size', width:12, control:'textbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "\xFE";
    z += "{ index:50 },\xFE";
    z += "{ index:50 },\xFE";
    z += "{name:'southview', index:51, label:'Bottom View', datatype: 'string', primarykey:false, width:50, control:'dropdownbox', required: false, notblank: false, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" },\xFE";
    z += "{name:'southmaster', index:17, label:'Master view', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:0, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewfixed', index:52, label:'Bottom fixed', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewslidable', index:53, label:'Bottom slidable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewclosable', index:54, label:'Bottom closable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewinitclosed', index:55, label:'Southv InitShut', width:12, control:'checkbox', canedit:true, required: false, notblank: true,  reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewinithidden', index:56, label:'Bottom initHidden', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewminsize', index:57, label:'Bottom MinSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewmaxsize', index:58, label:'Bottom MaxSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'southviewstartsize', defaultvalue:200, index:59, label:'Bottom Size', width:12, control:'textbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "\xFE";
    z += "{ index:70 },\xFE";
    z += "{ index:70 },\xFE";
    z += "{name:'westview', index:71, label:'Left View', datatype: 'string', primarykey:false, width:30, control:'dropdownbox', required: false, notblank: false, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" },\xFE";
    z += "{name:'westmaster', index:17, label:'Master view', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:0, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewfixed', index:72, label:'Left fixed', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewslidable', index:74, label:'Left slidable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewclosable', index:74, label:'Left closable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewinitclosed', index:75, label:'Left initClosed', width:12, control:'checkbox', canedit:true, required: false, notblank: true,  reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewinithidden', index:76, label:'Left initHidden', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewminsize', index:77, label:'Left MinSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewmaxsize', index:78, label:'Left MaxSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'westviewstartsize', defaultvalue:200, index:79, label:'Left Size', width:12, control:'textbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "\xFE";
    z += "{ index:90 },\xFE";
    z += "{ index:90 },\xFE";
    z += "{name:'eastview', index:91, label:'Right View', datatype: 'string', primarykey:false, width:30, control:'dropdownbox', required: false, notblank: false, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" },\xFE";
    z += "{name:'westmaster', index:17, label:'Master view', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:0, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewfixed', index:92, label:'Right fixed', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewslidable', index:94, label:'Right slidable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewclosable', index:94, label:'Right closable', width:12, control:'checkbox', canedit:true, required: false, notblank: true, defaultvalue:1, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewinitclosed', index:95, label:'Right initClosed', width:12, control:'checkbox', canedit:true, required: false, notblank: true,  reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewinithidden', index:96, label:'Right initHidden', width:12, control:'checkbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewminsize', index:97, label:'Right MinSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewmaxsize', index:98, label:'Right MaxSize', width:12, control:'textbox', canedit:true, required: false, notblank: false, defaultvalue:\"\", reflist: \"false,0;true,1\" },\xFE";
    z += "{name:'eastviewstartsize', defaultvalue:200, index:99, label:'Right Size', width:12, control:'textbox', canedit:true, required: false, notblank: true, reflist: \"false,0;true,1\" }\xFE";
    z += "\xFE";
    z += "\xFE";
    z += "********************************************************************************************************************\xFE";
    z += "************************************************** <%=nicePageName%> Layout Page **************************************\xFE";
    z += "*********************************************************************************************************************\xFE";
    z += "* EDITOR-OPTION: AUTO<%=''%>FORMAT\xFE";
    z += "*\xFE";
    z += "<% \xFE";
    z += "   nicePageName = @niceName(@DropIfRight(PageName, \".page\")) \xFE";
    z += "   NiceCenterViewName = @NiceName(@DropIfRight(pageModel.centerview, \".view\", true))\xFE";
    z += "   NiceNorthViewName = @NiceName(@DropIfRight(pageModel.northview, \".view\", true))\xFE";
    z += "   NiceSouthViewName = @NiceName(@DropIfRight(pageModel.southview, \".view\", true))\xFE";
    z += "   NiceEastViewName = @NiceName(@DropIfRight(pageModel.eastview, \".view\", true))\xFE";
    z += "   NiceWestViewName = @NiceName(@DropIfRight(pageModel.westview, \".view\", true))\xFE";
    z += "   \xFE";
    z += "   doLayout = NiceNorthViewName <> \"\" Or NiceSouthViewName <> \"\" Or NiceEastViewName <> \"\" Or NiceWestViewName <> \"\" \xFE";
    z += "   centerViewOnly = (NiceCenterViewName <> \"\") And (doLayout = False)\xFE";
    z += "%>\xFE";
    z += "*\xFE";
    z += "* Generated from template: <%=pageModel.templateName%>\xFE";
    z += "* \xFE";
    z += "Program <%=nicePageName%>\xFE";
    z += "<% If pageModel.pickpage Then %>\xFE";
    z += "   * You should setup your view to have a input URL-value with fromValue, and an output -url of ans\xFE";
    z += "<%End If%>\xFE";
    z += "   Dim fromPage As String = @QueryVar('fromPage')\xFE";
    z += "   Dim fromTcl As String = formVar('_attcl_')\xFE";
    z += "\xFE";
    z += "   <%$include _minimumRole%>\xFE";
    z += "      \xFE";
    z += "   <%if NiceCenterViewName Then %> \xFE";
    z += "      centerviewVars = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true, masterview: <%=centermaster%>}\xFE";
    z += "      Call view_<%=NiceCenterViewName%>_Setup(centerviewVars)\xFE";
    z += "   <%End If%>\xFE";
    z += "   <%if NiceNorthViewName Then %> \xFE";
    z += "      northviewVars = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true, masterview: <%=northmaster%>}\xFE";
    z += "      Call view_<%=NiceNorthViewName%>_Setup(northviewVars)\xFE";
    z += "   <%End If%>\xFE";
    z += "   <%if NiceSouthViewName Then %> \xFE";
    z += "      SouthviewVars = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true, masterview: <%=southmaster%>}\xFE";
    z += "      Call view_<%=NiceSouthViewName%>_Setup(SouthviewVars)\xFE";
    z += "   <%End If%>\xFE";
    z += "   <%if NiceEastViewName Then %> \xFE";
    z += "      EastviewVars = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true, masterview: <%=eastmaster%>}\xFE";
    z += "      Call view_<%=NiceEastViewName%>_Setup(EastviewVars)\xFE";
    z += "   <%End If%>\xFE";
    z += "   <%if NiceWestViewName Then %> \xFE";
    z += "      WestviewVars = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true, masterview: <%=westmaster%>}\xFE";
    z += "      Call view_<%=NiceWestViewName%>_Setup(WestviewVars)\xFE";
    z += "   <%End If%>\xFE";
    z += "\xFE";
    z += "   if @IspostBack Then\xFE";
    z += "      * Process user's requests\xFE";
    z += "      pageBtn = @FormVar('pageBtn')\xFE";
    z += "      ColumnID = Field(@formvar(\"contextMenuVal\"), \":\", 2)\xFE";
    z += "      if Left(ColumnID, 4) = \"LBL_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "      if Left(ColumnID, 4) = \"ctl_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "   \xFE";
    z += "      <%if NiceCenterViewName Then %> \xFE";
    z += "         Call view_<%=NiceCenterViewName%>_Unload(centerviewVars)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceNorthViewName Then %> \xFE";
    z += "         Call view_<%=NiceNorthViewName%>_Unload(northviewVars)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceSouthViewName Then %> \xFE";
    z += "         Call view_<%=NiceSouthViewName%>_Unload(SouthviewVars)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceEastViewName Then %> \xFE";
    z += "         Call view_<%=NiceEastViewName%>_Unload(EastviewVars)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceWestViewName Then %> \xFE";
    z += "         Call view_<%=NiceWestViewName%>_Unload(WestviewVars)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%If Right(LCase(pageModel.templateName),4) = \"form\" Then%>\xFE";
    z += "          * Re-Display the updated record, in case we MsgBox\xFE";
    z += "          Print @(-1):; // Clears output & reset activePage internal variable\xFE";
    z += "          Html = @displaypage_<%=nicePageName%>(centerviewVars, northviewVars, SouthviewVars, EastviewVars, WestviewVars)\xFE";
    z += "          <% If pageModel.theme Then%>\xFE";
    z += "                Html = @jsb_themes.<%=pageModel.theme%>(\"<%=projectName%>\", \"<%=nicePageName%>\", Html)\xFE";
    z += "          <% End If%>\xFE";
    z += "          Print Html:\xFE";
    z += "      <% End If%>\xFE";
    z += "\xFE";
    z += "      <%if NiceCenterViewName Then %> \xFE";
    z += "         Call view_<%=NiceCenterViewName%>_checkCommands(centerviewVars, pageBtn, ColumnID)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceNorthViewName Then %> \xFE";
    z += "         Call view_<%=NiceNorthViewName%>_checkCommands(northviewVars, pageBtn, ColumnID)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceSouthViewName Then %> \xFE";
    z += "         Call view_<%=NiceSouthViewName%>_checkCommands(SouthviewVars, pageBtn, ColumnID)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceEastViewName Then %> \xFE";
    z += "         Call view_<%=NiceEastViewName%>_checkCommands(EastviewVars, pageBtn, ColumnID)\xFE";
    z += "      <%End If%>\xFE";
    z += "      <%if NiceWestViewName Then %> \xFE";
    z += "         Call view_<%=NiceWestViewName%>_checkCommands(WestviewVars, pageBtn, ColumnID)\xFE";
    z += "      <%End If%>\xFE";
    z += "\xFE";
    z += "      * Any page level commands?\xFE";
    z += "      select case pageBtn\xFE";
    z += "         case \"addPageView\"\xFE";
    z += "            If @IsAdmin Then Call @jsb_mdl.page_addView(\"<%=ProjectName%>\", \"<%=PageName%>\", \"\")\xFE";
    z += "\xFE";
    z += "         case \"B\", \"B!\", \"Q\", \"Q!\": \xFE";
    z += "            If @QueryVar('fromPage') Then @Response.Redirect(fromPage) \xFE";
    z += "            <% If pageModel.pickpage Then %> \xFE";
    z += "                @response.redirect(\"close_html?ans=\" & UrlEncode(QueryVar(\"fromValue\")))\xFE";
    z += "            <%Else%>\xFE";
    z += "                Stop @ClearScreen:@Script(\"if (parent.refreshData) parent.refreshData();\")\xFE";
    z += "            <%End If%>\xFE";
    z += "\xFE";
    z += "         case \"C\", \"C!\"\xFE";
    z += "            If @QueryVar('fromPage') Then @Response.Redirect(fromPage)  \xFE";
    z += "            If @hasTclParent Or @hasParentProcess Then Stop @ClearScreen:@Script(\"if (parent.refreshData) parent.refreshData();\")\xFE";
    z += "            //Print @Script('window.close'):\xFE";
    z += "            @Server.end\xFE";
    z += "      end select\xFE";
    z += "    end if\xFE";
    z += "    \xFE";
    z += "    Print @(-1): // Clear Screen\xFE";
    z += "    \xFE";
    z += "    Html = @displaypage_<%=nicePageName%>(centerviewVars, northviewVars, SouthviewVars, EastviewVars, WestviewVars)\xFE";
    z += "    <% If pageModel.theme Then%>\xFE";
    z += "        Html = @jsb_themes.<%=pageModel.theme%>(\"<%=projectName%>\", \"<%=@DropIfRight(pageName, \".page\")%>\", Html)\xFE";
    z += "    <% End If%>\xFE";
    z += "    \xFE";
    z += "    Print Html:\xFE";
    z += "End Program\xFE";
    z += "\xFE";
    z += "Function displaypage_<%=nicePageName%>(centerviewVars, northviewVars, SouthviewVars, EastviewVars, WestviewVars)\xFE";
    z += "   PageBtns = \"\"\xFE";
    z += "   <% If !pageModel.canceltxt Then pageModel.canceltxt = 'Cancel' %>\xFE";
    z += "   <% If !pageModel.backtxt Then pageModel.backtxt = 'Back' %>\xFE";
    z += "   <% If !pageModel.quittxt Then pageModel.quittxt = 'Quit' %>\xFE";
    z += "\xFE";
    z += "   <% If pageModel.cancelbtn Or pageModel.backbtn Then %>\xFE";
    z += "       * We must have someplace to go back to for a Quit or Back button\xFE";
    z += "       fromPage = @QueryVar('fromPage')\xFE";
    z += "       If @hasTclParent Or fromPage Or @hasParentProcess Then \xFE";
    z += "          <% If pageModel.cancelbtn Then %>\xFE";
    z += "             PageBtns = PageBtns:@SubmitBtn('pageBtn', 'B', '<%=pageModel.canceltxt%>')\xFE";
    z += "    \xFE";
    z += "          <% ElseIf pageModel.backbtn Then %>\xFE";
    z += "             PageBtns = PageBtns:@SubmitBtn('pageBtn', 'B', '<%=pageModel.backtxt%>')\xFE";
    z += "    \xFE";
    z += "          <% End If %>\xFE";
    z += "          <% If pageModel.cancelbtn Then %>\xFE";
    z += "       Else\xFE";
    z += "             PageBtns = PageBtns:@SubmitBtn('pageBtn', 'C', '<%=pageModel.canceltxt%>') ;* Cancel edit only\xFE";
    z += "          <% End If %>\xFE";
    z += "       End If\xFE";
    z += "   <% End If %>\xFE";
    z += "   \xFE";
    z += "   <%if NiceCenterViewName Then %>\xFE";
    z += "      centerviewVars.extraToolBarHtml = PageBtns\xFE";
    z += "      MainHtml = @display_<%=NiceCenterViewName%>(centerviewVars)\xFE";
    z += "   <%Else%>\xFE";
    z += "      MainHtml = PageBtns\xFE";
    z += "   <%End If%>\xFE";
    z += "\xFE";
    z += "   <%if NiceSouthViewName Then %>\xFE";
    z += "      SouthHtml = @display_<%=NiceSouthViewName%>(SouthviewVars)\xFE";
    z += "      <% SOpts = \"\"\xFE";
    z += "         If pageModel.southviewfixed Then SOpts = SOpts:\"Fixed,\"\xFE";
    z += "         If pageModel.southviewslidable Then SOpts = SOpts:\"Slidable,\"\xFE";
    z += "         If pageModel.southviewclosable Then SOpts = SOpts:\"Closable,\"\xFE";
    z += "         If pageModel.southviewinitclosed Then SOpts = SOpts:\"InitClosed,\"\xFE";
    z += "         If pageModel.southviewinithidden Then SOpts = SOpts:\"InitHidden,\"\xFE";
    z += "         If pageModel.southviewminsize Then SOpts = SOpts:\"MinSize:\":pageModel.southviewminsize:\",\"\xFE";
    z += "         If pageModel.southviewmaxsize Then SOpts = SOpts:\"MaxSize:\":pageModel.southviewminsize:\",\"\xFE";
    z += "         If pageModel.southviewstartsize Then SOpts = SOpts:\"StartSize:\":pageModel.southviewstartsize:\",\"\xFE";
    z += "      %>SOpts = \"<%=SOpts%>\"\xFE";
    z += "   <%ElseIf doLayout Then %>\xFE";
    z += "      southHtml = \"\"\xFE";
    z += "      SOpts = \"\"\xFE";
    z += "   <%End If%>\xFE";
    z += "   \xFE";
    z += "   <%if NiceNorthViewName Then %> \xFE";
    z += "      NorthHtml = @display_<%=NiceNorthViewName%>(northviewVars)\xFE";
    z += "      <% NOpts = \"\"\xFE";
    z += "         If pageModel.northviewfixed Then NOpts = NOpts:\"Fixed,\"\xFE";
    z += "         If pageModel.northviewslidable Then NOpts = NOpts:\"Slidable,\"\xFE";
    z += "         If pageModel.northviewclosable Then NOpts = NOpts:\"Closable,\"\xFE";
    z += "         If pageModel.northviewinitclosed Then NOpts = NOpts:\"InitClosed,\"\xFE";
    z += "         If pageModel.northviewinithidden Then NOpts = NOpts:\"InitHidden,\"\xFE";
    z += "         If pageModel.northviewminsize Then NOpts = NOpts:\"MinSize:\":pageModel.northviewminsize:\",\"\xFE";
    z += "         If pageModel.northviewmaxsize Then NOpts = NOpts:\"MaxSize:\":pageModel.northviewminsize:\",\"\xFE";
    z += "         If pageModel.northviewstartsize Then NOpts = NOpts:\"StartSize:\":pageModel.northviewstartsize:\",\"\xFE";
    z += "      %>NOpts = \"<%=NOpts%>\"\xFE";
    z += "   <%ElseIf doLayout Then %>\xFE";
    z += "      NorthHtml = \"\"\xFE";
    z += "      NOpts = \"\"\xFE";
    z += "   <%End If%>\xFE";
    z += "\xFE";
    z += "   <%if NiceEastViewName Then %>\xFE";
    z += "      EastHtml = @display_<%=NiceEastViewName%>(EastviewVars)\xFE";
    z += "      <% EOpts = \"\"\xFE";
    z += "         If pageModel.eastviewfixed Then EOpts = EOpts:\"Fixed,\"\xFE";
    z += "         If pageModel.eastviewslidable Then EOpts = EOpts:\"Slidable,\"\xFE";
    z += "         If pageModel.eastviewclosable Then EOpts = EOpts:\"Closable,\"\xFE";
    z += "         If pageModel.eastviewinitclosed Then EOpts = EOpts:\"InitClosed,\"\xFE";
    z += "         If pageModel.eastviewinithidden Then EOpts = EOpts:\"InitHidden,\"\xFE";
    z += "         If pageModel.eastviewminsize Then EOpts = EOpts:\"MinSize:\":pageModel.eastviewminsize:\",\"\xFE";
    z += "         If pageModel.eastviewmaxsize Then EOpts = EOpts:\"MaxSize:\":pageModel.eastviewminsize:\",\"\xFE";
    z += "         If pageModel.eastviewstartsize Then EOpts = EOpts:\"StartSize:\":pageModel.eastviewstartsize:\",\"\xFE";
    z += "      %>EOpts = \"<%=EOpts%>\"\xFE";
    z += "   <%ElseIf doLayout Then %>\xFE";
    z += "      eastHtml = \"\"\xFE";
    z += "      EOpts = \"\"\xFE";
    z += "   <%End If%>\xFE";
    z += "   <%if NiceWestViewName Then %>\xFE";
    z += "      WestHtml = @display_<%=NiceWestViewName%>(WestviewVars)\xFE";
    z += "      <% WOpts = \"\"\xFE";
    z += "         If pageModel.westviewfixed Then WOpts = WOpts:\"Fixed,\"\xFE";
    z += "         If pageModel.westviewslidable Then WOpts = WOpts:\"Slidable,\"\xFE";
    z += "         If pageModel.westviewclosable Then WOpts = WOpts:\"Closable,\"\xFE";
    z += "         If pageModel.westviewinitclosed Then WOpts = WOpts:\"InitClosed,\"\xFE";
    z += "         If pageModel.westviewinithidden Then WOpts = WOpts:\"InitHidden,\"\xFE";
    z += "         If pageModel.westviewminsize Then WOpts = WOpts:\"MinSize:\":pageModel.westviewminsize:\",\"\xFE";
    z += "         If pageModel.westviewmaxsize Then WOpts = WOpts:\"MaxSize:\":pageModel.westviewminsize:\",\"\xFE";
    z += "         If pageModel.westviewstartsize Then WOpts = WOpts:\"StartSize:\":pageModel.westviewstartsize:\",\"\xFE";
    z += "      %>WOpts = \"<%=WOpts%>\"\xFE";
    z += "   <%ElseIf doLayout Then%>\xFE";
    z += "      westHtml = \"\"\xFE";
    z += "      WOpts = \"\"\xFE";
    z += "   <%End If%>\xFE";
    z += "\xFE";
    z += "   <%If doLayout Then %>\xFE";
    z += "      Return @LAYOUT(MainHtml, NorthHtml, NOpts, SouthHtml, SOpts, EastHtml, EOpts, WestHtml, WOpts)\xFE";
    z += "   <%ElseIf centerViewOnly Then %>\xFE";
    z += "      Return MainHtml\xFE";
    z += "   <%Else%>\xFE";
    z += "      If @IsAdmin Then Return @SubmitBtn('pageBtn', 'addPageView', 'Add a view')\xFE";
    z += "      Return \"\"\xFE";
    z += "   <%End If%>\xFE";
    z += "End Function\xFE";
    z += "\xFE";
    z += "// This is a Call from the Themes allowing us to modify / extend the Theme Menu\xFE";
    z += "Subroutine <%=nicePageName%>_customMenu(MenuBar)\xFE";
    z += "    // Examples:\xFE";
    z += "    //\xFE";
    z += "    //    MenuBar.NewMenu = {}\xFE";
    z += "    //    MenuBar.NewMenu.MenuName = { id: 'gotoPage' } \xFE";
    z += "    //\xFE";
    z += "    //    If MenuBar.Admin Then MenuBar.Admin.diabled = True\xFE";
    z += "    //\xFE";
    z += "End Subroutine\xFE";
    z += "\xFE";
    z += "<%\xFE";
    z += "    // Process all templates for this page\xFE";
    z += "    For Each ViewName in @jsb_mdl.ViewsInPage(ProjectName, pageName)\xFE";
    z += "        ViewName = @DropIfRight(ViewName, \".view\", true):\".view\"\xFE";
    z += "\xFE";
    z += "        xtraResults = \"\"\xFE";
    z += "        If !@Jsb_mdl.GenerateCodeFromTemplate(ProjectName, \"JSB_viewTemplates\", pageName, pageModel, ViewName, xtraResults, compileResults, noModelingStuff) Then Errors = compileResults; Return \"\"\xFE";
    z += "\xFE";
    z += "        %>\xFE";
    z += "        <%=xtraResults%>\xFE";
    z += "        <%\xFE";
    z += "    Next\xFE";
    z += "\xFE";
    z += "    Results := @jsb_mdl.UpdateCode(Join(Gen, \"\"), ProjectName, nicePageName)\xFE";
    z += "    Gen = []\xFE";
    z += "    If InStr(Results, \"^\") Then Errors = Results\xFE";
    z += "    \xFE";
    z += "    * Do Menu\xFE";
    z += "    Call @jsb_mdl.UpdateMenu(ProjectName)\xFE";
    z += "%>"
    window.cached_jsb_pagetemplates["layoutpage"] = z;
    var z = "{ index:15 },\xFE";
    z += "{name: 'centerview', index:16, label:'View', datatype: 'string', primarykey:false, width:30, control:'combobox', required: false, notblank: false, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" },\xFE";
    z += "{name: 'swipeform', index:16, label:'Swipe Form', datatype: 'boolean', primarykey:false, width:30, control:'checkbox', required: false, notblank: false, canedit:true, reflist: \"false,0;true,1\"  }\xFE";
    z += "******************************************************************************\xFE";
    z += "<% \xFE";
    z += "    nicePageName = @niceName(@DropIfRight(pageName, \".page\", True));\xFE";
    z += "    \xFE";
    z += "    pageModel.centerview = LCase(pageModel.centerview)\xFE";
    z += "    If Right(pageModel.centerview, 5) <> \".view\" Then pageModel.centerview := '.view'\xFE";
    z += "    NiceViewName = @niceName(@DropIfRight(pageModel.centerview, \".view\", True));\xFE";
    z += "    If !NiceViewName Then Errors = 'You need to define a View for this page ':pageName; Return \"\"\xFE";
    z += "    \xFE";
    z += "    ReadJSon childModel From @fHandle(\"DICT\", ProjectName), pageModel.centerview Else\xFE";
    z += "        Ans = @MsgBox(\"Warning\", \"The view \":pageModel.centerview:\" does not exist, do you want to create it?\", \"*Yes,No\")\xFE";
    z += "        If Ans <> \"Yes\" Then Errors = \"Canceled by user\"; Return \"\"\xFE";
    z += "        childModel = @Jsb_mdl.createNewView(pageModel.centerview)\xFE";
    z += "        WriteJSon childModel On @fHandle(\"DICT\", ProjectName), pageModel.centerview Else Stop @(-1):\"edv-\":System(28):\": \":@Errors\xFE";
    z += "        Call @Jsb_mdl.GenerateView(ProjectName, pageModel.centerview, False)\xFE";
    z += "    End If\xFE";
    z += "    \xFE";
    z += "%>\xFE";
    z += "* EDITOR-OPTION: AUTO<%=''%>FORMAT\xFE";
    z += "******************************************************************************\xFE";
    z += "Program <%=nicePageName%>\xFE";
    z += "    Dim fromPage As String = @QueryVar('fromPage')\xFE";
    z += "    Dim fromTcl As String = formVar('_attcl_')\xFE";
    z += "\xFE";
    z += "    <%$Include _minimumRole%>\xFE";
    z += "      \xFE";
    z += "    Dim centerviewVars As Json = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true }\xFE";
    z += "    Call View_<%=NiceViewName%>_Setup(centerviewVars)\xFE";
    z += "    \xFE";
    z += "    If @isPostBack And !fromTcl Then\xFE";
    z += "        * Figure out what the user clicked\xFE";
    z += "        Dim pageBtn As String = @FormVar('pageBtn')\xFE";
    z += "        Dim ColumnID As String = Field(@FormVar(\"contextMenuVal\"), \":\", 2)\xFE";
    z += "        If Left(ColumnID, 4) = \"LBL_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        If Left(ColumnID, 4) = \"ctl_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        \xFE";
    z += "        * Unload the form elements\xFE";
    z += "        Call View_<%=NiceViewName%>_Unload(centerviewVars)\xFE";
    z += "        \xFE";
    z += "        * Process the user command\xFE";
    z += "        Call View_<%=NiceViewName%>_checkCommands(centerviewVars, pageBtn, ColumnID)\xFE";
    z += "    End If\xFE";
    z += "    \xFE";
    z += "    Print @(-1):; // Clears output & reset activePage internal variable\xFE";
    z += "    <% If pageModel.theme Then%>\xFE";
    z += "    * Build and output HTML in user's theme\xFE";
    z += "    Print @Jsb_themes.<%=pageModel.theme%>(\"<%=projectName%>\", \"<%=@DropIfRight(pageName, \".page\")%>\", @Display_<%=NiceViewName%>(centerviewVars)):\xFE";
    z += "    <%ELse %>\xFE";
    z += "    * Build and output HTML\xFE";
    z += "    Print @Display_<%=NiceViewName%>(centerviewVars):\xFE";
    z += "    <% End If%>\xFE";
    z += "    \xFE";
    z += "    * We will stop here, and wait for the user to click on something\xFE";
    z += "    if @hasTclParent Then @Server.Pause\xFE";
    z += "End Program\xFE";
    z += "\xFE";
    z += "\xFE";
    z += "// This is a Call Back from the Themes allowing us to modify / extend the Theme Menu\xFE";
    z += "Subroutine <%=nicePageName%>_customMenu(ByRef MenuBar As JSON)\xFE";
    z += "   * Placeholder\xFE";
    z += "End Subroutine\xFE";
    z += "\xFE";
    z += "<%\xFE";
    z += "    // Process all templates for this page\xFE";
    z += "For Each ViewName As String In @Jsb_mdl.ViewsInPage(ProjectName, pageName)\xFE";
    z += "    ViewName = @DropIfRight(ViewName, \".view\", True):\".view\"\xFE";
    z += "    \xFE";
    z += "    If !@Jsb_mdl.GenerateCodeFromTemplate(ProjectName, \"JSB_viewTemplates\", pageName, pageModel, ViewName, xtraResults, compileResults, noModelingStuff) Then Errors = compileResults; Return \"\"\xFE";
    z += "    %>\xFE";
    z += "    <%=xtraResults%>\xFE";
    z += "    <%\xFE";
    z += "Next\xFE";
    z += "        \xFE";
    z += "Results := @Jsb_mdl.UpdateCode(Join(Gen, \"\"), ProjectName, nicePageName)\xFE";
    z += "Gen = []\xFE";
    z += "If Instr(Results, \"^\") Then Errors = Results\xFE";
    z += "        \xFE";
    z += "    * Do Menu\xFE";
    z += "Call @Jsb_mdl.UpdateMenu(ProjectName)\xFE";
    z += "%>\xFE";
    z += ""
    window.cached_jsb_pagetemplates["simplepage"] = z;
    var z = "{ index:15 },\xFE";
    z += "{name: 'centerview', Newlineprefix: True, index:16, label:'View', datatype: 'string', primarykey:False, width:30, control:'dropdownbox', required: False, notblank: False, canedit:True, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" }\xFE";
    z += "\xFE";
    z += "********************************************************************************************************************\xFE";
    z += "************************************************** <%=nicePageName%> Page ******************************************\xFE";
    z += "********************************************************************************************************************\xFE";
    z += "* EDITOR-OPTION: AUTO<%=''%>FORMAT\xFE";
    z += "*\xFE";
    z += "<% nicePageName = @niceName(@DropIfRight(pageName, \".page\")); niceViewName = @niceName(@DropIfRight(pageModel.centerview, \".view\", True)); If !niceViewName Then Errors = 'You need to define a View for this page'; Return \"\"\xFE";
    z += "%>\xFE";
    z += "*\xFE";
    z += "*\xFE";
    z += "* Generated from page template: <%=pageModel.templateName%>\xFE";
    z += "* \xFE";
    z += "Program <%=nicePageName%>\xFE";
    z += "$Options Js\xFE";
    z += "    fromPage = @QueryVar('fromPage')\xFE";
    z += "    <%$Include _minimumRole%>\xFE";
    z += "      \xFE";
    z += "    viewVars = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true }\xFE";
    z += "    Call View_<%=niceViewName%>_Setup(viewVars)\xFE";
    z += "    \xFE";
    z += "    $('meta[name=\"viewport\"]').attr('content', 'width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1')\xFE";
    z += "    window.myBP = System(27)\xFE";
    z += "\xFE";
    z += "    <%\xFE";
    z += "    ViewName = @DropIfRight(pageModel.centerview, \".view\", True):\".view\"\xFE";
    z += "    ReadJSon dataSetView From @fHandle(\"DICT\", ProjectName), ViewName Else Errors = ViewName:\" not found in dict \":ProjectName; Return \"\"\xFE";
    z += "    allColumns = []\xFE";
    z += "    For Each Column In dataSetView.columns\xFE";
    z += "        If Column.name And Column.display <> \"hidden\" And Column.display <> \"gridhidden\" Then allColumns[-1] = Column.name\xFE";
    z += "    Next\xFE";
    z += "    firstField = allColumns[LBound(allColumns)]\xFE";
    z += "    %>\xFE";
    z += "    \xFE";
    z += "    Container = \"<div class='container' style-'position: absolute; margin-top: 20px;' >\"\xFE";
    z += "    Container := \"   <div class='form-group row'>\" ;*  Style='margin-top: 40%; height: 20%'\xFE";
    z += "    Container := \"      <style>\"\xFE";
    z += "    Container := \"         .form-control        { font-size: 90px !important; height: 1.4em !important; }\"\xFE";
    z += "    Container := \"         .form-control-label  { font-size: 20px !important; height: 1.5em !important; }\"\xFE";
    z += "    Container := \"         .ui-autocomplete     { bottom: 20px; font-size: 20px !important; overflow-y: auto; overflow-x: hidden }\"\xFE";
    z += "    Container := \"         select option        { font-size: 38px }\"\xFE";
    z += "    Container := \"         input[type=checkbox] { transform: scale(4); margin-left: 1em; margin-top: 1.4em; font-size: small !important }\"\xFE";
    z += "    Container := \"         label                { overflow: hidden }\"\xFE";
    z += "    Container := \"      </style>\"\xFE";
    z += "    Container := \"      <div id='swipeDiv' style='position: absolute; left: 0; top: 0; width: 100%; bottom: 0'></div>\"\xFE";
    z += "    Container := \"   </div>\"\xFE";
    z += "    Container := \"</div>\"\xFE";
    z += "    Container = @Html(Container)\xFE";
    z += "    \xFE";
    z += "    Container = Display_<%=niceViewName%>_extras(viewVars, Container)\xFE";
    z += "    \xFE";
    z += "    <% If pageModel.theme Then %>\xFE";
    z += "    Print @(-1):@Jsb_themes.<%=pageModel.theme%>(\"<%=projectName%>\", \"<%=@DropIfRight(pageName, \".page\")%>\", Container):\xFE";
    z += "    <% Else %>\xFE";
    z += "    Print @(-1):Container:\xFE";
    z += "    <% End If %>\xFE";
    z += "    @Server.Flush\xFE";
    z += "    \xFE";
    z += "    fieldName = \"<%=NiceName(firstField)%>\"\xFE";
    z += "    window.row = viewVars.Row\xFE";
    z += "    CS_Prefix = System(27):\".swipe_<%=NiceViewName%>_\"\xFE";
    z += "    Cs = CS_Prefix:fieldName\xFE";
    z += "    Call @Cs(PrintTxt, pageLeft, pageRight) ;* Get Preview For The First Field\xFE";
    z += "    Html = window.convertPrint2Html(PrintTxt)\xFE";
    z += "    \xFE";
    z += "    Loop\xFE";
    z += "        $('#swipeDiv').html(Html)\xFE";
    z += "        window.pageRight = pageRight ;* this Will Be Used For The Previews And The Returned Formvar('btn')\xFE";
    z += "        window.pageLeft = pageLeft\xFE";
    z += "        Call @Jsb_bf.enableSwiping(viewVars.Row) ;* this Will Pause And Wait For A Response\xFE";
    z += "\xFE";
    z += "        * Process user's requests\xFE";
    z += "        pageBtn = @FormVar('pageBtn'):@FormVar('btn')\xFE";
    z += "        ColumnID = Field(@FormVar(\"contextMenuVal\"), \":\", 2)\xFE";
    z += "        If Left(ColumnID, 4) = \"LBL_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        If Left(ColumnID, 4) = \"ctl_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        \xFE";
    z += "        Call View_<%=niceViewName%>_Unload(viewVars, fieldName)\xFE";
    z += "        \xFE";
    z += "        If pageBtn = pageRight Or pageBtn = pageLeft Then\xFE";
    z += "            fieldName = Mid(pageBtn, Len(CS_Prefix)+1)\xFE";
    z += "            Call @pageBtn(PrintTxt, pageLeft, pageRight) ;* Get Preview For The Field\xFE";
    z += "            Html = window.convertPrint2Html(PrintTxt)\xFE";
    z += "        Else\xFE";
    z += "            Call View_<%=niceViewName%>_checkCommands(viewVars, pageBtn, ColumnID)\xFE";
    z += "        End If\xFE";
    z += "    While 1 Do Repeat\xFE";
    z += "End Program\xFE";
    z += "\xFE";
    z += "Program <%=nicePageName%>\xFE";
    z += "    $Options Aspx\xFE";
    z += "    fromPage = @QueryVar('fromPage')\xFE";
    z += "    <%$Include _minimumRole%>\xFE";
    z += "      \xFE";
    z += "    centerviewVars = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true }\xFE";
    z += "    Call View_<%=niceViewName%>_Setup(centerviewVars)\xFE";
    z += "    \xFE";
    z += "    Loop\xFE";
    z += "        Print @(-1): // Clear Screen\xFE";
    z += "        Html = @Display_<%=niceViewName%>(centerviewVars)\xFE";
    z += "        \xFE";
    z += "        <% If pageModel.theme Then%>\xFE";
    z += "        Html = @Jsb_themes.<%=pageModel.theme%>(\"<%=projectName%>\", \"<%=@DropIfRight(pageName, \".page\")%>\", Html)\xFE";
    z += "        <% End If%>\xFE";
    z += "        Print Html:\xFE";
    z += "        \xFE";
    z += "        @Server.Pause\xFE";
    z += "        \xFE";
    z += "        * Process user's requests\xFE";
    z += "        pageBtn = @FormVar('pageBtn')\xFE";
    z += "        ColumnID = Field(@FormVar(\"contextMenuVal\"), \":\", 2)\xFE";
    z += "        If Left(ColumnID, 4) = \"LBL_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        If Left(ColumnID, 4) = \"ctl_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        \xFE";
    z += "        Call View_<%=niceViewName%>_Unload(centerviewVars)\xFE";
    z += "        \xFE";
    z += "        Call View_<%=niceViewName%>_checkCommands(centerviewVars, pageBtn, ColumnID)\xFE";
    z += "    While 1 Do Repeat\xFE";
    z += "End Sub\xFE";
    z += "\xFE";
    z += "// This is a Call from the Themes allowing us to modify / extend the Theme Menu\xFE";
    z += "Subroutine <%=nicePageName%>_customMenu(MenuBar)\xFE";
    z += "    // Examples:\xFE";
    z += "    //\xFE";
    z += "    //    MenuBar.NewMenu = {}\xFE";
    z += "    //    MenuBar.NewMenu.MenuName = { id: 'gotoPage' } \xFE";
    z += "    //\xFE";
    z += "    //    If MenuBar.Admin Then MenuBar.Admin.diabled = True\xFE";
    z += "    //\xFE";
    z += "End Subroutine\xFE";
    z += "\xFE";
    z += "<%\xFE";
    z += "    // Process all templates for this page\xFE";
    z += "For Each ViewName In @Jsb_mdl.ViewsInPage(ProjectName, pageName)\xFE";
    z += "    ViewName = @DropIfRight(ViewName, \".view\", True):\".view\"\xFE";
    z += "\xFE";
    z += "    xtraResults = \"\"\xFE";
    z += "    If !@Jsb_mdl.GenerateCodeFromTemplate(ProjectName, \"JSB_viewTemplates\", pageName, pageModel, ViewName, xtraResults, compileResults, noModelingStuff) Then Errors = compileResults; Return \"\"\xFE";
    z += "\xFE";
    z += "    %>\xFE";
    z += "    <%=xtraResults%>\xFE";
    z += "    <%\xFE";
    z += "Next\xFE";
    z += "\xFE";
    z += "Results := @Jsb_mdl.UpdateCode(Join(Gen, \"\"), ProjectName, nicePageName)\xFE";
    z += "Gen = []\xFE";
    z += "If Instr(Results, \"^\") Then Errors = Results\xFE";
    z += "    \xFE";
    z += "    * Do Menu\xFE";
    z += "Call @Jsb_mdl.UpdateMenu(ProjectName)\xFE";
    z += "%>"
    window.cached_jsb_pagetemplates["swipepage"] = z;
    var z = "{ index:15 },\xFE";
    z += "{name: 'westview', index:16, label:'Master view', datatype: 'string', primarykey:false, width:30, control:'combobox', required: true, notblank: true, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" },\xFE";
    z += "{name: 'centerview', index:17, label:'Slave view', datatype: 'string', primarykey:false, width:30, control:'combobox', required: true, notblank: true, canedit:true, pickfunction: 'edv_pick?projectName={projectname}', reffile:\"dict {projectname}\", refpk:\"ItemID\", refwhere:\"ItemID Like '%.view'\" }\xFE";
    z += "********************************************************************************************************************\xFE";
    z += "************************************************** <%=nicePageName%> Page ******************************************\xFE";
    z += "********************************************************************************************************************\xFE";
    z += "* EDITOR-OPTION: AUTO<%=''%>FORMAT\xFE";
    z += "*\xFE";
    z += "<% nicePageName = @niceName(@DropIfRight(pageName, \".page\", True));\xFE";
    z += "MasterViewName = pageModel.westview\xFE";
    z += "SlaveViewName = pageModel.centerview\xFE";
    z += "MasterViewName = DropIfRight(MasterViewName, \".view\", True):\".view\"\xFE";
    z += "SlaveViewName = DropIfRight(SlaveViewName, \".view\", True):\".view\"\xFE";
    z += "\xFE";
    z += "Readjson MasterView From fHandle(\"JSB_viewTemplates\"), MasterViewName Else MasterView = {}\xFE";
    z += "\xFE";
    z += "ReadJSon masterModel From @fHandle(\"DICT\", ProjectName), MasterViewName Else\xFE";
    z += "Ans = @MsgBox(\"Warning\", \"The view \":MasterViewName:\" does not exist, do you want to create it?\", \"*Yes,No\")\xFE";
    z += "If Ans <> \"Yes\" Then Errors = \"Canceled by user\"; Return \"\"\xFE";
    z += "masterModel = @Jsb_mdl.createNewView(MasterViewName)\xFE";
    z += "WriteJSon masterModel On @fHandle(\"DICT\", ProjectName), MasterViewName Else Stop @(-1):\"edv-\":System(28):\": \":@Errors\xFE";
    z += "Call @Jsb_mdl.GenerateView(ProjectName, MasterViewName, False)\xFE";
    z += "End If\xFE";
    z += "\xFE";
    z += "ReadJSon slaveModel From @fHandle(\"DICT\", ProjectName), SlaveViewName Else\xFE";
    z += "Ans = @MsgBox(\"Warning\", \"The view \":SlaveViewName:\" does not exist, do you want to create it?\", \"*Yes,No\")\xFE";
    z += "If Ans <> \"Yes\" Then Errors = \"Canceled by user\"; Return \"\"\xFE";
    z += "slaveModel = @Jsb_mdl.createNewView(SlaveViewName)\xFE";
    z += "WriteJSon slaveModel On @fHandle(\"DICT\", ProjectName), SlaveViewName Else Stop @(-1):\"edv-\":System(28):\": \":@Errors\xFE";
    z += "Call @Jsb_mdl.GenerateView(ProjectName, SlaveViewName, False)\xFE";
    z += "End If\xFE";
    z += "\xFE";
    z += "NiceMasterViewName = @niceName(@DropIfRight(MasterViewName, \".view\", True));\xFE";
    z += "NiceSlaveViewName = @niceName(@DropIfRight(SlaveViewName, \".view\", True));\xFE";
    z += "If !NiceMasterViewName Or !NiceSlaveViewName Then Errors = 'You need to define two Views for this page'; Return \"\" %>\xFE";
    z += "*\xFE";
    z += "* Generated from page template: <%=pageModel.templateName%>\xFE";
    z += "* \xFE";
    z += "Program <%=nicePageName%>\xFE";
    z += "    Dim fromPage As String = @QueryVar('fromPage')\xFE";
    z += "    Dim fromTcl As String = formVar('_attcl_')\xFE";
    z += "    \xFE";
    z += "    <%$Include _minimumRole%>\xFE";
    z += "      \xFE";
    z += "    Dim MasterViewVars As Json = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: false, masterview: true }\xFE";
    z += "    Call View_<%=NiceMasterViewName%>_Setup(MasterViewVars)\xFE";
    z += "    \xFE";
    z += "    Dim SlaveViewVars As Json = { showAddRmvViews: true, fromParentPage: \"<%=pageName%>\", parentMultiView: '', lastView: true, masterview: false }\xFE";
    z += "    Call View_<%=NiceSlaveViewName%>_Setup(SlaveViewVars)\xFE";
    z += "    \xFE";
    z += "    If @isPostBack And !fromTcl Then\xFE";
    z += "        * Process user's requests\xFE";
    z += "        Dim pageBtn As String = @FormVar('pageBtn')\xFE";
    z += "        Dim ColumnID As String = Field(@FormVar(\"contextMenuVal\"), \":\", 2)\xFE";
    z += "        If Left(ColumnID, 4) = \"LBL_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        If Left(ColumnID, 4) = \"ctl_\" Then ColumnID = Mid(ColumnID, 5)\xFE";
    z += "        \xFE";
    z += "        Call View_<%=NiceMasterViewName%>_Unload(MasterViewVars)\xFE";
    z += "        Call View_<%=NiceSlaveViewName%>_Unload(SlaveViewVars)\xFE";
    z += "        \xFE";
    z += "        Dim contextMenuCmd As String = @FormVar(\"contextMenuCmd\")\xFE";
    z += "        Dim contextMenuVal As String = Field(@FormVar(\"contextMenuVal\"), \":\", 1)\xFE";
    z += "        \xFE";
    z += "        If contextMenuVal = \"<%=NiceMasterViewName%>\" Then\xFE";
    z += "            Call View_<%=NiceMasterViewName%>_checkCommands(MasterViewVars, pageBtn, ColumnID)\xFE";
    z += "            \xFE";
    z += "        ElseIf contextMenuVal = \"<%=NiceSlaveViewName%>\" Then\xFE";
    z += "            Call View_<%=NiceSlaveViewName%>_checkCommands(SlaveViewVars, pageBtn, ColumnID)\xFE";
    z += "            \xFE";
    z += "        Else\xFE";
    z += "            // Some commands, like SAVE, don't specify a specific Master or Slave view\xFE";
    z += "            <%If MasterView.templateName = \"Grid\" Then %>\xFE";
    z += "            Call View_<%=NiceSlaveViewName%>_checkCommands(SlaveViewVars, pageBtn, ColumnID)\xFE";
    z += "            Call View_<%=NiceMasterViewName%>_checkCommands(MasterViewVars, pageBtn, ColumnID)\xFE";
    z += "            <%Else%>\xFE";
    z += "            Call View_<%=NiceMasterViewName%>_checkCommands(MasterViewVars, pageBtn, ColumnID)\xFE";
    z += "            Call View_<%=NiceSlaveViewName%>_checkCommands(SlaveViewVars, pageBtn, ColumnID)\xFE";
    z += "            <%End If%>\xFE";
    z += "        End If\xFE";
    z += "        \xFE";
    z += "    End If\xFE";
    z += "    \xFE";
    z += "    Dim HtmlMaster As String = @Display_<%=NiceMasterViewName%>(MasterViewVars)\xFE";
    z += "    Dim HtmlSlave As String = @Display_<%=NiceSlaveViewName%>(SlaveViewVars)\xFE";
    z += "    \xFE";
    z += "    HtmlMaster = Replace(HtmlMaster, \"col-xs-12 col-sm-2 col-md-2 col-lg-1\", \"col-xs-12\")\xFE";
    z += "    HtmlMaster = Replace(HtmlMaster, \"col-xs-12 col-sm-4 col-md-4 col-lg-3\", \"col-xs-12\")\xFE";
    z += "    HtmlMaster = Replace(HtmlMaster, '<div class=\"container\">', '<div class=\"container\" style=\"display:table-cell\">')\xFE";
    z += "    Dim Html As String = Layout(HtmlSlave, \"\", \"\" /* NorthOptions */, \"\", \"\" /* SouthOptions */, \"\", \"\" /* EastOptions */, HtmlMaster, \"startsize: 200, minSize:100\")\xFE";
    z += "    \xFE";
    z += "    <% If pageModel.theme Then%>\xFE";
    z += "    * Build and output HTML in user's theme\xFE";
    z += "    Html = @Jsb_themes.<%=pageModel.theme%>(\"<%=projectName%>\", \"<%=@DropIfRight(pageName, \".page\", true)%>\", Html)\xFE";
    z += "    <% End If%>\xFE";
    z += "    \xFE";
    z += "    Print @(-1):; // Clears output & reset activePage internal variable\xFE";
    z += "    Print Html:\xFE";
    z += "    \xFE";
    z += "    * We will stop here, and wait for the user to click on something\xFE";
    z += "    if @hasTclParent Then @Server.Pause\xFE";
    z += "End Program\xFE";
    z += "\xFE";
    z += "// This is a Call from the Themes allowing us to modify / extend the Theme Menu\xFE";
    z += "Subroutine <%=nicePageName%>_customMenu(MenuBar As JSON)\xFE";
    z += "    // Examples:\xFE";
    z += "    //\xFE";
    z += "    //    MenuBar.NewMenu = {}\xFE";
    z += "    //    MenuBar.NewMenu.MenuName = { id: 'gotoPage' } \xFE";
    z += "    //\xFE";
    z += "    //    If MenuBar.Admin Then MenuBar.Admin.diabled = True\xFE";
    z += "    //\xFE";
    z += "End Subroutine\xFE";
    z += "\xFE";
    z += "<%\xFE";
    z += "    // Process all templates for this page\xFE";
    z += "For Each ViewName In @Jsb_mdl.ViewsInPage(ProjectName, pageName)\xFE";
    z += "    ViewName = @DropIfRight(ViewName, \".view\", True):\".view\"\xFE";
    z += "\xFE";
    z += "    xtraResults = \"\"\xFE";
    z += "    If !@Jsb_mdl.GenerateCodeFromTemplate(ProjectName, \"JSB_viewTemplates\", pageName, pageModel, ViewName, xtraResults, compileResults, noModelingStuff) Then Errors = compileResults; Return \"\"\xFE";
    z += "\xFE";
    z += "    %>\xFE";
    z += "    <%=xtraResults%>\xFE";
    z += "    <%\xFE";
    z += "Next\xFE";
    z += "\xFE";
    z += "Results := @Jsb_mdl.UpdateCode(Join(Gen, \"\"), ProjectName, nicePageName)\xFE";
    z += "Gen = []\xFE";
    z += "If Instr(Results, \"^\") Then Errors = Results\xFE";
    z += "    \xFE";
    z += "    * Do Menu\xFE";
    z += "Call @Jsb_mdl.UpdateMenu(ProjectName)\xFE";
    z += "%>\xFE";
    z += "\xFE";
    z += "    "
    window.cached_jsb_pagetemplates["twoviews"] = z;
    var z = "   Dim roleMsg As String = Iff(@IsAuthenticated, \"\", \"You must be logged in to view this page. \":@Anchor(@LoginUrl(\"\"), \"Click here to login\"))\xFE";
    z += "   <%\xFE";
    z += "   Select Case LCase(pageModel.minimumRole)\xFE";
    z += "      Case \"admin\"\xFE";
    z += "         %>If !@IsAdmin Then Stop Iff(roleMsg, roleMsg,  \"You must be an administrator to view this page.\")<%\xFE";
    z += "      Case \"director\"\xFE";
    z += "         %>If !@IsDirector Then Stop Iff(roleMsg, roleMsg,  \"You must be at least a director to view this page.\")<%\xFE";
    z += "      Case \"manager\"\xFE";
    z += "         %>If !@IsManager Then Stop Iff(roleMsg, roleMsg,  \"You must be at least a manager to view this page.\")<%\xFE";
    z += "      Case \"clerk\"\xFE";
    z += "         %>If !@IsClerk Then Stop Iff(roleMsg, roleMsg,  \"You must be at least a clerk to view this page.\")<%\xFE";
    z += "      Case \"employee\"\xFE";
    z += "         %>If !@IsEmployee Then Stop Iff(roleMsg, roleMsg,  \"You must be at least an employee to view this page.\")<%\xFE";
    z += "      Case \"user\"\xFE";
    z += "         %>If !@IsAuthenticated Then Stop roleMsg<%\xFE";
    z += "   End Select%>\xFE";
    z += "   \xFE";
    z += "    "
    window.cached_jsb_pagetemplates["_minimumrole"] = z;
}
anonymousFunc()
anonymousFunc = null